### ISSUE TITLE
AppImage on Ubuntu 22.04

### ISSUE THREAD

**Issue by alandefreitas** [Electrum-RVN-SIG/electrum-ravencoin#56]
The AppImage doesn't run. The output is:

```bash
./electrum-ravencoin-0.5.2-x86_64_00032d6c665aabb95c004f6fcdae3b7e.AppImage 
cannot find currencies.json. will regenerate it now.
Bittrex error
CoinGecko error
Traceback (most recent call last):
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/site-packages/electrum/exchange_rate.py", line 253, in query_all_exchanges_for_their_ccys_over_network
    await group.spawn(get_currencies_safe(name, exchange))
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 382, in __aexit__
    raise TaskTimeout(self._secs) from None
aiorpcx.curio.TaskTimeout: task timed out after 10s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_electremlWXB/usr/bin/electrum-ravencoin", line 93, in <module>
    from electrum.logging import get_logger, configure_logging  # import logging submodule first
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/site-packages/electrum/__init__.py", line 28, in <module>
    from . import daemon
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/site-packages/electrum/daemon.py", line 53, in <module>
    from .exchange_rate import FxThread
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/site-packages/electrum/exchange_rate.py", line 265, in <module>
    CURRENCIES = get_exchanges_and_currencies()
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/site-packages/electrum/exchange_rate.py", line 257, in get_exchanges_and_currencies
    asyncio.run(query_all_exchanges_for_their_ccys_over_network())
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/tmp/.mount_electremlWXB/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
```

**Comment by kralverde** [comment]
tracking on this, i believe its fixed in code, try adding an empty currencies.json to your electrum folder

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/409782979dde223b95b667278fe333e212d631be
