### ISSUE TITLE
unhandled exception in scripts

### ISSUE THREAD

**Issue by momettang** [Electrum-RVN-SIG/electrum-ravencoin#57]
When I run electrum-ravencoin-0.5.2.exe in Windows 10 (of course I have tried another asset, the result is same),
![image](https://user-images.githubusercontent.com/49330644/194716934-5b3537a0-2c2a-49f1-9e59-5ddb9b68d4d3.png)

The detail information of the windows is :
Traceback (most recent call last):
  File "electrum\exchange_rate.py", line 253, in query_all_exchanges_for_their_ccys_over_network
  File "aiorpcx\curio.py", line 382, in __aexit__
aiorpcx.curio.TaskTimeout: task timed out after 10s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_electrum", line 93, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "electrum\__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "electrum\daemon.py", line 53, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "electrum\exchange_rate.py", line 265, in <module>
  File "electrum\exchange_rate.py", line 257, in get_exchanges_and_currencies
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
asyncio.exceptions.CancelledError

What shall I do to slove the issue?

**Comment by kralverde** [comment]
create an empty file called 'currencies.json' in your electrum folder

**Comment by momettang** [comment]
It working. Thank you very much.
