### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Electrum-RVN-SIG** [Electrum-RVN-SIG/electrum-ravencoin#66]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
Traceback (most recent call last):
  File "/home/work/workspace/electrum-ravencoin/electrum/gui/qt/my_treeview.py", line 314, in mouseDoubleClickEvent
    self.on_double_click(idx)
  File "/home/work/workspace/electrum-ravencoin/electrum/gui/qt/address_list.py", line 124, in on_double_click
    self.main_window.show_address(addr)
  File "/home/work/workspace/electrum-ravencoin/electrum/gui/qt/main_window.py", line 1059, in show_address
    None + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electrum-Ravencoin Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.4.3-104-g0969bbcb3-dirty  | 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] | Linux-6.2.0-26-generic-x86_64-with-glibc2.35 | standard | en_US | [ℹ](https://crashhub.rvn4lyfe.com//crash/1) | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by Electrum-RVN-SIG** [comment]
test
