### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by mio-19** [Electrum-RVN-SIG/electrum-ravencoin#67]
```
Traceback (most recent call last):
  File "electrum\exchange_rate.py", line 253, in query_all_exchanges_for_their_ccys_over_network
  File "aiorpcx\curio.py", line 382, in __aexit__
aiorpcx.curio.TaskTimeout: task timed out after 10s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_electrum", line 93, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "electrum\__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "electrum\daemon.py", line 53, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "electrum\exchange_rate.py", line 265, in <module>
  File "electrum\exchange_rate.py", line 257, in get_exchanges_and_currencies
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
asyncio.exceptions.CancelledError

```

**Comment by kralverde** [comment]
Could you try https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v1.0.0
