### ISSUE TITLE
Cannot export history

### ISSUE THREAD

**Issue by poblabs** [Electrum-RVN-SIG/electrum-ravencoin#8]
On Windows full install and on portable version, I cannot export history. 

Version 0.3.0

Wallet > History > Export > CSV:

```
Traceback
Traceback (most recent call last):
  File "electrum\gui\qt\history_list.py", line 1098, in export_history_dialog
  File "electrum\gui\qt\history_list.py", line 1106, in do_export_history
  File "electrum\util.py", line 519, in <lambda>
  File "electrum\util.py", line 514, in do_profile
  File "electrum\wallet.py", line 1030, in get_detailed_history
AttributeError: 'RavenValue' object has no attribute 'value'

Additional information
Electrum version: 0.3.0 
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] 
Operating system: Windows-10-10.0.19041-SP0 
Wallet type: standard,imported 
Locale: en_US 
```

**Comment by kralverde** [comment]
Thank you. A fix will be included in the next update.

**Comment by kralverde** [comment]
Patched in https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/b45863b3c48a31bc4eb577af5088fcf94015f341
Will close this issue once public testing of the 0.4.0 release is complete

**Comment by poblabs** [comment]
I'm still having this issue in the 0.4.0 Portable version (I don't run the full install version)

```
Traceback
Traceback (most recent call last):
  File "electrum\gui\qt\history_list.py", line 1099, in export_history_dialog
  File "electrum\gui\qt\history_list.py", line 1107, in do_export_history
  File "electrum\util.py", line 527, in <lambda>
  File "electrum\util.py", line 522, in do_profile
  File "electrum\wallet.py", line 1046, in get_detailed_history
  File "electrum\transaction.py", line 183, in __lt__
ValueError: RavenValue required
 
Additional information
Electrum version: 0.4.0 
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] 
Operating system: Windows-10-10.0.19041-SP0 
Wallet type: standard 
Locale: en_US 
```

**Comment by poblabs** [comment]
Deleting my wallet data directory and letting version 0.4.0 create a new one has resolved this for me.
